### ISSUE TITLE
host.otp isnt detemplated in user-data

### ISSUE THREAD

**Issue by ddoc** [theforeman/community-templates#169]
I am using user-data templates on ec2 and @host.otp is not populated.

In the first case the value is simply blank, but when I get the user-data using curl the otp is there. This is on foreman 1. 7

My workaround: http://pastie.org/10063791

**Comment by mmoll** [comment]
I'm not sure if that's a problem of core, templates or the configuration here. @stbenjam, could you have a look?

**Comment by stbenjam** [comment]
It's quite possible though that it doesn't get done for user data, because it's a different path in the code (as you noticed, it works with curl - that goes through the right code path).  Would you mind filing  an issue at 
http://projects.theforeman.org/projects/foreman/issues/new? I'm surprised no one noticed until now.

**Comment by mmoll** [comment]
created http://projects.theforeman.org/issues/10119

**Comment by mmoll** [comment]
no reaction, closing.

**Comment by wzzrd** [comment]
Can this be reopened? I'm seeing this exact same thing and filed a [downstream bug](https://bugzilla.redhat.com/show_bug.cgi?id=1392620) for it.

**Comment by mmoll** [comment]
@wzzrd please open a new upstream bug for it and set "related to" to http://projects.theforeman.org/issues/10119.

**Comment by wzzrd** [comment]
Done. Also linked downstream BZ.

http://projects.theforeman.org/issues/17292
