### ISSUE TITLE
Installation of puppet-agent fails

### ISSUE THREAD

**Issue by sarah-peter** [theforeman/community-templates#303]
Hello,

since a few days, when I provision a new VM (in this case Ubuntu 16.04.1 LTS) it fails during the "Select and install software" step with the error

> WARNING: The following packages cannot be authenticated!
> puppet-agent

![puppet_auth_issue](https://cloud.githubusercontent.com/assets/5088268/19191171/821e87c6-8ca1-11e6-9194-a4d064462fa9.jpg)

**Comment by mmoll** [comment]
I guess it has to do with PuppetLabs' new GPG key, will have a look...

**Comment by mmoll** [comment]
https://tickets.puppetlabs.com/browse/CPR-384

**Comment by mmoll** [comment]
It seems this is https://bugs.launchpad.net/ubuntu/+source/base-installer/+bug/1553121

**Comment by sarah-peter** [comment]
Thanks for investigating @mmoll! Since the issue is quite old and still not solved, do you have a work-around for the meantime?

**Comment by mmoll** [comment]
@diehlsa not really... I did some further investigations back then and can saw exactly the same bvehaviour as one of the reporters of the Ubuntu issue: the key is listed correctly when using apt-key, but not still not trusted when installing the packge. What you could try is to switch over the install to the finish script and install http://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb and then puppet-agent, maybe that works.

In general, if that issue is not getting fixed in the installer, I'm out of ideas here.

**Comment by mmoll** [comment]
#313 would implement that.
